[project]
name = "link-shortener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-multipart>=0.0.20",
]

[dependency-groups]
dev = [
    "pytest-asyncio>=0.25.3",
]
