name: Run Tests

on: [push, pull_request]

jobs:
  test:
    name: Python Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install project dependencies
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests
